#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    ports:
       - 8000:8000
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000

    #bash -c "python /code/mysite/manage.py migrate && python /code/mysite/manage.py runserver 0.0.0.0:8000"
