#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    ports:
       - 8000:8000
      
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000
    depends_on: 
       - redis
   
  redis:
     image: redis:6.0-rc3-buster
     ports:
      - "6379:6379"





# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     depends_on:
#       - redis
#   redis:
#     image: redis:6.0-rc3-buster
#     ports:
#     - "6379:6379"