#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    expose:
       - 8000  
    user: "1001:1002"
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000
    depends_on: 
       - redis

  nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - web
    ports:
      - 80:80
    links:
      - web:web
   
  redis:
     image: redis:6.0-rc3-buster
     ports:
      - "6379:6379"


