# Generated by Django 3.1.1 on 2020-10-10 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20201010_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='suggestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.suggestionmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
