# Generated by Django 3.1.1 on 2020-12-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201010_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionmodel',
            name='date_input',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='suggestionmodel',
            name='time_input',
            field=models.TimeField(null=True),
        ),
    ]
